LA FUENTE QUE USAREMOS ES MONTSERRAT Y SU RESPECTIVA FAMILIA SIN UTILIZAR NI ITALIC NI BOLD


LA PALETA DE COLORES ES LA SIGUIENTE:
VERDE CLARO:  008c43
VERDE OSCURO: 164b31
NEGRO:           333
GRIS:         d1d3c4


